[tracking]
pw = ""

[url]
subscription = ""
form = ""

[mention]
substack_icon = "https://camo.githubusercontent.com/3d4121e2061fe8a37e532bc8485e2ef0f8dbfaa26fe0f7e53f755df91d8a4333/68747470733a2f2f737562737461636b2e636f6d2f696d672f737562737461636b2e706e67"
substack_url = ""
twitter_url = ""
linkedin_icon = "https://play-lh.googleusercontent.com/kMofEFLjobZy_bCuaiDogzBcUT-dz3BBbOrIEjJ-hqOabjK8ieuevGe6wlTD15QzOqw=w480-h960-rw"
linkedin_url = ""

[firestore]
type = ""
project_id = ""
private_key_id = ""
private_key = ""
client_email = ""
client_id = ""
auth_uri = ""
token_uri = ""
auth_provider_x509_cert_url = ""
client_x509_cert_url = ""
universe_domain = ""